# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_D5ntBa7m8nauzBBcaaKqtgWTH836T_
"""

import numpy as np
import datetime

precios = {}

comprador = {}

ubicaciones_ocupadas = {}
asistentes = {}


def mostrar_menu():
      print("CONCIERTO VIP MICHAEL JAM")
      print("1. Comprar entradas")
      print("2. Mostrar Ubicaciones Disponibles")
      print("3. Ver listado de asistentes")
      print("4. Mostrar ganancias totales")
      print("Salir")

def comprar_entradas():

      while True:
        entrada_1 = int(input('Escoge el asiento de tu primera entrada'))
        rut_entrada_1 = int(input("añade tu rut sin guión ni digito verificador"))
        if rut_entrada_1 > 8 and rut_entrada_1 == 0:
            print("rut inválido")
            return
        if entrada_1 < 1 and entrada_1 > 100:
            print("entrada inválida")
            return
        if entrada_1 > 1 and entrada_1 <= 100:
          tipo_entrada_1 = input("Escoge el tipo de entrada('PLATINUM $120000','GOLD $80000','SILVER $50000)").upper()
          if tipo_entrada_1 == 'PLATINUM':
            precios[120000]
          if tipo_entrada_1 == 'GOLD':
            precios.append[80000]
          if tipo_entrada_1 == 'SILVER':
            precios.append[50000]
          print(f"Usted ha escogido la entrada número{entrada_1} y tipo {tipo_entrada_1}")
          print('1','2','3','4','5','6','7','8','9','10')
          print('11','12','13','14','15','16','17','18','19','20')
          print('21', '22', '23', '24', '25', '26', '27', '28', '29', '30')
          print('31', '32', '33', '34', '35', '36', '37', '38', '39', '40')
          print('41', '42', '43', '44', '45', '46', '47', '48', '49', '50')
          print('51', '52', '53', '54', '55', '56', '57', '58', '59', '60')
          print('61', '62', '63', '64', '65', '66', '67', '68', '69', '70')
          print('71', '72', '73', '74', '75', '76', '77', '78', '79', '80')
          print('81', '82', '83', '84', '85', '86', '87', '88', '89', '90')
          print('91', '92', '93', '94', '95', '96', '97', '98', '99', '100')
          continue

          otra2= input("¿quieres una segunda entrada? (Si/No)").upper()
          if otra2 == 'NO':
            break
            if otra2 == 'SI':
                continue
        entrada_2 = int(input("Escoge el asiento de tu segunda entrada"))
        rut_entrada_2 = int(input("añade tu rut sin guión ni digito verificador"))
        if rut_entrada_2 > 8 and rut_entrada_2 == 0:
            print("rut inválido")
            return
        if entrada_2 < 1 and entrada_2 > 100:
              print("entrada inválida")
              return
        elif entrada_2 > 1 and entrada_2 <= 100:
          tipo_entrada_2 = input("Escoge el tipo de entrada('PLATINUM $120000','GOLD $80000','SILVER $50000)")
          if tipo_entrada_2 == 'PLATINUM':
            precios.append[120000]
          if tipo_entrada_2 == 'GOLD':
            precios.append[80000]
          if tipo_entrada_2 == 'SILVER':
            precios.append[50000]
          print(f"Usted ha escogido la entrada número{entrada_2} y tipo {tipo_entrada_2}")
          print('1','2','3','4','5','6','7','8','9','10')
          print('11','12','13','14','15','16','17','18','19','20')
          print('21', '22', '23', '24', '25', '26', '27', '28', '29', '30')
          print('31', '32', '33', '34', '35', '36', '37', '38', '39', '40')
          print('41', '42', '43', '44', '45', '46', '47', '48', '49', '50')
          print('51', '52', '53', '54', '55', '56', '57', '58', '59', '60')
          print('61', '62', '63', '64', '65', '66', '67', '68', '69', '70')
          print('71', '72', '73', '74', '75', '76', '77', '78', '79', '80')
          print('81', '82', '83', '84', '85', '86', '87', '88', '89', '90')
          print('91', '92', '93', '94', '95', '96', '97', '98', '99', '100')
          continue
        otra3= input("¿quieres una tercera entrada? (Si/No)").upper()
        if otra3 == 'NO':
              break
        if otra3 == 'SI':
          continue
        entrada_3 = int(input("Escoge el asiento de tu tercera entrada"))
        rut_entrada_3 = int(input("añade tu rut sin guión ni digito verificador"))
        if rut_entrada_3 > 8 and rut_entrada_3 == 0:
            print("rut inválido")
            return
        if entrada_3 < 1 and entrada_3 > 100:
          print("Entrada inválida.")
        if entrada_3 >= 1 and entrada_3 <= 100:
          tipo_entrada_3 = input("Escoge el tipo de entrada('PLATINUM $120000','GOLD $80000','SILVER $50000)")
          if tipo_entrada_3 == 'PLATINUM':
            precios.append[120000]
          if tipo_entrada_3 == 'GOLD':
            precios.append[80000]
          if tipo_entrada_3 == 'SILVER':
            precios.append[50000]
          print(f"Usted ha escogido la entrada número{entrada_3} y tipo {tipo_entrada_3}")
          print('1','2','3','4','5','6','7','8','9','10')
          print('11','12','13','14','15','16','17','18','19','20')
          print('21', '22', '23', '24', '25', '26', '27', '28', '29', '30')
          print('31', '32', '33', '34', '35', '36', '37', '38', '39', '40')
          print('41', '42', '43', '44', '45', '46', '47', '48', '49', '50')
          print('51', '52', '53', '54', '55', '56', '57', '58', '59', '60')
          print('61', '62', '63', '64', '65', '66', '67', '68', '69', '70')
          print('71', '72', '73', '74', '75', '76', '77', '78', '79', '80')
          print('81', '82', '83', '84', '85', '86', '87', '88', '89', '90')
          print('91', '92', '93', '94', '95', '96', '97', '98', '99', '100')
        ubicaciones_ocupadas = (entrada_1, entrada_2, entrada_3)
        asistentes = {rut_entrada_1, rut_entrada_2, rut_entrada_3}
        break

def mostrar_ubicaciones_disponibles():
      while True:
          print(f"estas ubicaciones están ocupadas{ubicaciones_ocupadas}")
          print("puedes escoger cualquiera de las demás")

          print('1','2','3','4','5','6','7','8','9','10')
          print('11','12','13','14','15','16','17','18','19','20')
          print('21', '22', '23', '24', '25', '26', '27', '28', '29', '30')
          print('31', '32', '33', '34', '35', '36', '37', '38', '39', '40')
          print('41', '42', '43', '44', '45', '46', '47', '48', '49', '50')
          print('51', '52', '53', '54', '55', '56', '57', '58', '59', '60')
          print('61', '62', '63', '64', '65', '66', '67', '68', '69', '70')
          print('71', '72', '73', '74', '75', '76', '77', '78', '79', '80')
          print('81', '82', '83', '84', '85', '86', '87', '88', '89', '90')
          print('91', '92', '93', '94', '95', '96', '97', '98', '99', '100')
          break

def ver_listado_asistentes():
      while True:
          print(f"Los asistentes registrados son {asistentes}")
          break

def mostrar_ganancias_totales():
          print(f"las ganancias totales acumuladas según cada entrada son {precios}")

while True:
  def mostrar_menu():
    opcion1 = input("¿Quieres comprar entradas? (SI/NO)").upper()
    if opcion1 == 'SI':
    def comprar_entradas():
    elif opcion1 == 'NO':
    return
    opcion2 = input("¿Quieres ver ubicaciones disponibles? (SI/NO)").upper()
    if opcion2 == 'SI':
      def mostrar_ubicaciones_disponibles():
      elif opcion2 == 'NO':
        return
      opcion3 = input("¿Quieres ver listado de asistentes? (SI/NO)").upper()
        if opcion3 == 'SI':
          def ver_listado_asistentes():
        elif opcion3 == 'NO':
          return
        opcion4 = input("¿Quieres ver las ganancias totales? (SI/NO)").upper()
          if opcion4 == 'SI':
            def mostrar_ganancias_totales():
            if opcion4 == 'NO':
              return